c = ('Palmeiras', 'Santos', 'Corintians', 'São paulo', 'Vasco', 'atletico', 'Flamengo', 'Bahia')
print('-=-' * 30)
print(f'lista de times: {c}')
print('-=-' * 30)
print(f'os 5 primeiros são {c[0:5]}')
print('-=-' * 30)
print(f'os ultimos 4 colocados {c[-4:]}')
print('-=-' * 30)
print(f'os times em ordem alfabetica {sorted(c)}')
print('-=-' * 30)
print(f'o corintians estar na {c.index("Corintians")+1} posição')
print('-=-' * 30)
